<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * GameRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GameRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return Query
     */
    public function findAllQuery()
    {
        return $this->createQueryBuilder('g')
            ->getQuery()
        ;
    }
}
