<?php

namespace AppBundle\Repository;

/**
 * HomepageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HomepageRepository extends \Doctrine\ORM\EntityRepository
{
}
