<?php

namespace AppBundle\Repository;

use Doctrine\ORM\Query;

/**
 * PlayerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PlayerRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @param $name
     * @return Query
     */
    public function findByNameQuery($name)
    {
        return $this->createQueryBuilder('p')
            ->where('p.name LIKE :name')
            ->setParameter(':name', sprintf('%%s%', $name))
            ->getQuery()
        ;
    }
}
