index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

country:
    path:      country/{id}
    defaults:  { _controller: AppBundle:Country:index }

player:
    path:      player/{id}
    defaults:  { _controller: AppBundle:Player:index }

coach:
    path:      coach/{id}
    defaults:  { _controller: AppBundle:Coach:index }

team:
    path:      team/{id}
    defaults:  { _controller: AppBundle:Team:index }
