index:
    path:      /
    defaults:  { _controller: AppBundle:Default:index }

country:
    path:      country/{name}
    defaults:  { _controller: AppBundle:Country:index }
#    requirements:
#        name: England|France|Albania|Austria|Belgium|Croatia|Czech|Germany|Hungary|Iceland|Ireland|Italy|Northern_Ireland|Poland|Portugal|Russia|Romania|Slovakia|Spain|Switzerland|Sweden|Turkey|Wales|Ukraine

player:
    path:      player/{country}/{id}
    defaults:  { _controller: AppBundle:Player:index }
#    requirements:
#        country: England|France|Albania|Austria|Belgium|Croatia|Czech|Germany|Hungary|Iceland|Ireland|Italy|Northern_Ireland|Poland|Portugal|Russia|Romania|Slovakia|Spain|Switzerland|Sweden|Turkey|Wales|Ukraine
#        id:  \d+

coach:
    path:      coach/{country}/{id}
    defaults:  { _controller: AppBundle:Coach:index }
#    requirements:
#        country: England|France|Albania|Austria|Belgium|Croatia|Czech|Germany|Hungary|Iceland|Ireland|Italy|Northern_Ireland|Poland|Portugal|Russia|Romania|Slovakia|Spain|Switzerland|Sweden|Turkey|Wales|Ukraine

team:
    path:      team/{name}
    defaults:  { _controller: AppBundle:Team:index }
#    requirements:
#        name: England|France|Albania|Austria|Belgium|Croatia|Czech|Germany|Hungary|Iceland|Ireland|Italy|Northern_Ireland|Poland|Portugal|Russia|Romania|Slovakia|Spain|Switzerland|Sweden|Turkey|Wales|Ukraine

generator:
    path:      generator
    defaults:  { _controller: AppBundle:Generator:index }